version: '3.8'

services:
  stats-db:
    image: postgres:14
    container_name: stats-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - explore-network

  stats-server:
    build: stats/stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - explore-network

networks:
  explore-network:
    driver: bridge